{% set version = "2.5.0.0" %}
{% set name = "pycoQC" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "
  entry_points:
    - pycoQC=pycoQC.__main__:main_pycoQC
    - Fast5_to_seq_summary=pycoQC.__main__:main_Fast5_to_seq_summary
    - Barcode_split=pycoQC.__main__:main_Barcode_split
  noarch: "python"

requirements:
  build:
    - python == 3.6
    - pip>=19.2.1
    - ripgrep=11.0.1
  run:
    - python == 3.6
    - numpy == 1.17.1
    - scipy == 1.3.1
    - pandas == 0.25.1
    - plotly == 4.1.0
    - jinja2 == 2.10.1
    - h5py == 2.9.0
    - tqdm == 4.35.0
    - pysam == 0.15.3

test:
  imports:
    - pycoQC.pycoQC
    - pycoQC.Fast5_to_seq_summary
    - pycoQC.Barcode_split
  commands:
    - pycoQC --help
    - Fast5_to_seq_summary --help
    - Barcode_split --help

about:
  home: "https://github.com/a-slide/pycoQC"
  license: "GPLv3"
  summary: "PycoQC computes metrics and generates interactive QC plots for Oxford Nanopore technologies sequencing data"
